### ISSUE TITLE
Exception: Could not set v4l2 format

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pyv4l2#2]
```
EYE0 Process [WARNING] video_capture : Found ['Microsoft\xc2\xae LifeCam HD-5000'] as devices that match the src string pattern Using the first match.
WORLD Process [WARNING] video_capture : Found ['HD Webcam C615'] as devices that match the src string pattern Using the first match.
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rafael/greserved/pupil-o/pupil_src/capture/eye.py", line 145, in eye
    cap = autoCreateCapture(cap_src, cap_size, 30, timebase=g_pool.timebase)
  File "/home/rafael/greserved/pupil-o/pupil_src/shared_modules/video_capture/__init__.py", line 79, in autoCreateCapture
    cap = Camera_Capture(matching_devices[preferred_idx],filter_sizes(matching_devices[preferred_idx],size),fps,timebase)
  File "/home/rafael/greserved/pupil-o/pupil_src/shared_modules/video_capture/linux_video/__init__.py", line 68, in __init__
    self.capture = v4l2.Capture('/dev/video'+str(self.src_id))
  File "v4l2.pyx", line 309, in v4l2.Capture.__init__ (v4l2.c:6480)
  File "v4l2.pyx", line 690, in v4l2.Capture.transport_format.__set__ (v4l2.c:11939)
  File "v4l2.pyx", line 578, in v4l2.Capture.set_format (v4l2.c:10074)
Exception: Could not set v4l2 format
```

**Comment by cpicanco** [comment]
That is the issue I was talking about (https://github.com/pupil-labs/pupil/issues/210), would appreciate any help.

**Comment by cpicanco** [comment]
Restarting the ide (sublime text in my case) makes the error to stop.
